### ISSUE TITLE
Flash of unstyled content

### ISSUE THREAD

**Issue by bdrtsky** [nuxt-community/emotion-module#12]
Hello 👋 Thanks for this plugin, thanks to it we can easily use CSS-in-JS with Nuxt!

I noticed the issue when running SSR mode (build & start). If you refresh the page you can see unstyled markup for the moment. No errors in console. 

In generate mode everything works fine, so do in dev.

**Comment by bdrtsky** [comment]
Styles doesn't injected

<img width="1328" alt="Screenshot 2020-06-03 at 00 29 36" src="https://user-images.githubusercontent.com/45076741/83571981-6e41ad80-a531-11ea-955e-73df619f8a9e.png">

**Comment by bdrtsky** [comment]
A repro, if it could be helpful - https://github.com/bdrtsky/emotion-nuxt-issue

**Comment by codebender828** [comment]
Hey @bdrtsky . I just ran your project in gitpod. No changes. It looks like the styles are injected. So I got no FOUC. 🤔 

Wasn't able to reproduce it.

Here's the gitpod.
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/e57bcc22-01ca-4446-aa8f-7d053b4c3d71)

Could there be something else?

**Comment by pi0** [comment]
Hi @bdrtsky I can confirm repro has to issue. It is because you have to add `@nuxtjs/emotion` to `modules` not `buildModules`.

The reason is that module needs to hook into renderer injecting critical css used by page: [src](https://github.com/nuxt-community/emotion-module/blob/master/lib/module.js#L71)

**Comment by pi0** [comment]
I also noticed you are using custom plugin to inject `$css`. This bails advantages of [`babel-plugin-motion`](https://emotion.sh/docs/babel-plugin-emotion) for minification and optimization as it matches `styled` and `css` (also IDE integrations are same...)

**Comment by bdrtsky** [comment]
It work the same if I add to`modules`, I tried that 🤔
@pi0 did you tried it, it fixes for you?

**Comment by bdrtsky** [comment]
@codebender828 your video is dev env, it works fine there. In prod - you don't see FOAC because you don't have DevTools (with disabled cache) opened. Disable cache and you will see FOAC in prod.

**Comment by pi0** [comment]
> It work the same if I add tomodules, I tried that thinking
Yep. Maybe you forgot to remove the other `modules:[]` block? :D To confirm best is checking page source

**Comment by bdrtsky** [comment]
I renamed `buildModules ` to `modules`. There's a FOUC if you run `build && start` and then open DevTools with disabled cache.

**Comment by pi0** [comment]
Ensure not doing this: 

![image](https://user-images.githubusercontent.com/5158436/83619808-acb88600-a58c-11ea-90a0-6268cd0ce653.png)

**Comment by bdrtsky** [comment]
@pi0 lol. This is it. It did overwrite `modules`, I totally missed that. 

It seems all good now, so I'm closing this. Sorry for stupid issue, and huge thanks!
